/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Checkin;
import javax.swing.JOptionPane;

/**
 *
 * @author chinmayi_shaligram
 */
public class Create_Checkin extends javax.swing.JPanel {

    /**
     * Creates new form Create_Checkin
     */
    Checkin checkin;
    public Create_Checkin(Checkin checkin) {
        initComponents();
        
        this.checkin = checkin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_save = new javax.swing.JButton();
        Lbl_BName = new javax.swing.JLabel();
        Lbl_Routing = new javax.swing.JLabel();
        Lbl_Balance = new javax.swing.JLabel();
        Lbl_AccNo = new javax.swing.JLabel();
        txt_BName = new javax.swing.JTextField();
        Lbl_AccType = new javax.swing.JLabel();
        txt_BRouting = new javax.swing.JTextField();
        txt_AccNo = new javax.swing.JTextField();
        txt_Balance = new javax.swing.JTextField();
        Lbl_Savings = new javax.swing.JLabel();
        txt_Acctype = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        Btn_save.setText("save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });
        add(Btn_save);
        Btn_save.setBounds(240, 420, 75, 29);

        Lbl_BName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_BName.setText("Bank Name");
        add(Lbl_BName);
        Lbl_BName.setBounds(130, 200, 90, 17);

        Lbl_Routing.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Routing.setText("Routing Number");
        add(Lbl_Routing);
        Lbl_Routing.setBounds(130, 240, 170, 17);

        Lbl_Balance.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Balance.setText("Bank Balance");
        add(Lbl_Balance);
        Lbl_Balance.setBounds(130, 280, 100, 17);

        Lbl_AccNo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_AccNo.setText("Account Number");
        add(Lbl_AccNo);
        Lbl_AccNo.setBounds(130, 320, 170, 17);

        txt_BName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_BName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BNameActionPerformed(evt);
            }
        });
        add(txt_BName);
        txt_BName.setBounds(330, 200, 92, 20);

        Lbl_AccType.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_AccType.setText("Account Type");
        add(Lbl_AccType);
        Lbl_AccType.setBounds(130, 360, 100, 17);

        txt_BRouting.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_BRouting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BRoutingActionPerformed(evt);
            }
        });
        add(txt_BRouting);
        txt_BRouting.setBounds(330, 240, 92, 20);

        txt_AccNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_AccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AccNoActionPerformed(evt);
            }
        });
        add(txt_AccNo);
        txt_AccNo.setBounds(330, 280, 92, 20);

        txt_Balance.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Balance);
        txt_Balance.setBounds(330, 320, 92, 20);

        Lbl_Savings.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Lbl_Savings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Savings.setText("Checkings Account");
        add(Lbl_Savings);
        Lbl_Savings.setBounds(190, 120, 280, 30);

        txt_Acctype.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Acctype);
        txt_Acctype.setBounds(330, 360, 92, 20);
        add(jLabel3);
        jLabel3.setBounds(120, 90, 0, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/checkin.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(130, -410, 1180, 1080);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1080, 600);

        jLabel2.setPreferredSize(new java.awt.Dimension(1400, 800));
        jLabel2.setRequestFocusEnabled(false);
        add(jLabel2);
        jLabel2.setBounds(210, 80, 70, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        // TODO add your handling code here:

        checkin.setBank_Name1(txt_BName.getText());
        checkin.setBank_Routing1(txt_BRouting.getText());
        checkin.setBank_Balance1(txt_Balance.getText());
        checkin.setAccount_Type1(txt_AccNo.getText());
        checkin.setAccount_No1(txt_Acctype.getText());
        
        JOptionPane.showMessageDialog(this, "your information is saved.");
                
           
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void txt_BNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BNameActionPerformed

    private void txt_BRoutingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BRoutingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BRoutingActionPerformed

    private void txt_AccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AccNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_save;
    private javax.swing.JLabel Lbl_AccNo;
    private javax.swing.JLabel Lbl_AccType;
    private javax.swing.JLabel Lbl_BName;
    private javax.swing.JLabel Lbl_Balance;
    private javax.swing.JLabel Lbl_Routing;
    private javax.swing.JLabel Lbl_Savings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_AccNo;
    private javax.swing.JTextField txt_Acctype;
    private javax.swing.JTextField txt_BName;
    private javax.swing.JTextField txt_BRouting;
    private javax.swing.JTextField txt_Balance;
    // End of variables declaration//GEN-END:variables
}
