/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author chinmayi_shaligram
 */
public class Create_Person extends javax.swing.JPanel {
    

    /**
     * Creates new form Create_Person
     */
   
    Person person;
    public Create_Person(Person person) {
        initComponents();
        
       this.person = person;            //call value through main n assign value
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txt_Age = new javax.swing.JTextField();
        Txt_Ht = new javax.swing.JTextField();
        Txt_Wt = new javax.swing.JTextField();
        Txt_FN = new javax.swing.JTextField();
        Txt_SSN = new javax.swing.JTextField();
        Txt_LN = new javax.swing.JTextField();
        Btn_Save = new javax.swing.JButton();
        Txt_Phno = new javax.swing.JTextField();
        Txt_DOB = new javax.swing.JTextField();
        Lbl_Firstname = new javax.swing.JLabel();
        Lbl_LastName = new javax.swing.JLabel();
        Lbl_Phno = new javax.swing.JLabel();
        Lbl_DOB = new javax.swing.JLabel();
        Lbl_Age = new javax.swing.JLabel();
        Lbl_Height = new javax.swing.JLabel();
        Lbl_Weight = new javax.swing.JLabel();
        Lbl_SSN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText(" ");
        jLabel2.setPreferredSize(new java.awt.Dimension(1423, 768));

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel1);
        jLabel1.setBounds(90, 140, 513, 30);

        Txt_Age.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        Txt_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AgeActionPerformed(evt);
            }
        });
        add(Txt_Age);
        Txt_Age.setBounds(420, 250, 95, 20);

        Txt_Ht.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_HtActionPerformed(evt);
            }
        });
        add(Txt_Ht);
        Txt_Ht.setBounds(420, 300, 95, 20);

        Txt_Wt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Wt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_WtActionPerformed(evt);
            }
        });
        add(Txt_Wt);
        Txt_Wt.setBounds(420, 350, 95, 20);

        Txt_FN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_FN);
        Txt_FN.setBounds(170, 250, 100, 20);

        Txt_SSN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_SSN);
        Txt_SSN.setBounds(420, 400, 95, 20);

        Txt_LN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_LNActionPerformed(evt);
            }
        });
        add(Txt_LN);
        Txt_LN.setBounds(170, 300, 100, 20);

        Btn_Save.setText("Save");
        Btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SaveActionPerformed(evt);
            }
        });
        add(Btn_Save);
        Btn_Save.setBounds(270, 480, 75, 29);

        Txt_Phno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PhnoActionPerformed(evt);
            }
        });
        add(Txt_Phno);
        Txt_Phno.setBounds(170, 350, 100, 20);

        Txt_DOB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_DOB);
        Txt_DOB.setBounds(170, 400, 101, 20);

        Lbl_Firstname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Firstname.setText("First Name");
        add(Lbl_Firstname);
        Lbl_Firstname.setBounds(40, 250, 80, 16);

        Lbl_LastName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_LastName.setText("Last Name");
        add(Lbl_LastName);
        Lbl_LastName.setBounds(40, 300, 90, 17);

        Lbl_Phno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Phno.setText("Phone Number ");
        add(Lbl_Phno);
        Lbl_Phno.setBounds(40, 350, 106, 17);

        Lbl_DOB.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_DOB.setText("Date of Birth");
        add(Lbl_DOB);
        Lbl_DOB.setBounds(40, 400, 85, 17);

        Lbl_Age.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Age.setText("Age");
        add(Lbl_Age);
        Lbl_Age.setBounds(330, 240, 50, 30);

        Lbl_Height.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Height.setText("Height");
        add(Lbl_Height);
        Lbl_Height.setBounds(330, 300, 50, 17);

        Lbl_Weight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Weight.setText("Weight");
        add(Lbl_Weight);
        Lbl_Weight.setBounds(330, 350, 60, 17);

        Lbl_SSN.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_SSN.setText("SSN");
        add(Lbl_SSN);
        Lbl_SSN.setBounds(330, 400, 40, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(170, 120, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1080, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AgeActionPerformed

    private void Txt_HtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_HtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_HtActionPerformed

    private void Txt_WtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_WtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_WtActionPerformed

    private void Txt_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_LNActionPerformed

    private void Txt_PhnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PhnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PhnoActionPerformed

    private void Btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SaveActionPerformed
        // TODO add your handling code here:
        person.setFirst_Name(Txt_FN.getText());
        person.setLast_Name(Txt_LN.getText());
        person.setPhone_Num(Txt_Phno.getText());
        person.setDOB(Txt_DOB.getText());
        person.setAge(Txt_Age.getText());
        person.setHeight(Txt_Ht.getText());
        person.setWeight(Txt_Wt.getText());
        person.setSSN(Txt_SSN.getText());
       
        JOptionPane.showMessageDialog(this, "Your information has been saved.");
    }//GEN-LAST:event_Btn_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Save;
    private javax.swing.JLabel Lbl_Age;
    private javax.swing.JLabel Lbl_DOB;
    private javax.swing.JLabel Lbl_Firstname;
    private javax.swing.JLabel Lbl_Height;
    private javax.swing.JLabel Lbl_LastName;
    private javax.swing.JLabel Lbl_Phno;
    private javax.swing.JLabel Lbl_SSN;
    private javax.swing.JLabel Lbl_Weight;
    private javax.swing.JTextField Txt_Age;
    private javax.swing.JTextField Txt_DOB;
    private javax.swing.JTextField Txt_FN;
    private javax.swing.JTextField Txt_Ht;
    private javax.swing.JTextField Txt_LN;
    private javax.swing.JTextField Txt_Phno;
    private javax.swing.JTextField Txt_SSN;
    private javax.swing.JTextField Txt_Wt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
