/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;
import Model.Liscense;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author chinmayi_shaligram
 */
public class Create_Liscense extends javax.swing.JPanel {

    /**
     * Creates new form Create_Liscense1
     */
    Liscense liscense;
    public Create_Liscense(Liscense liscense) {
    initComponents();
    this.liscense = liscense;
    }

    public ImageIcon ResizeImage (String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(Lbl_Photo.getWidth(), Lbl_Photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_save = new javax.swing.JButton();
        txt_Liscense = new javax.swing.JTextField();
        txt_Issue = new javax.swing.JTextField();
        txt_Expiry = new javax.swing.JTextField();
        txt_Blood = new javax.swing.JTextField();
        Lbl_Liscense = new javax.swing.JLabel();
        Lbl_Issue = new javax.swing.JLabel();
        Lbl_Expiry = new javax.swing.JLabel();
        Lbl_Blood = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Lbl_Photo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Driver's Liscense");
        add(jLabel1);
        jLabel1.setBounds(160, 170, 317, 30);

        Btn_save.setText("Save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });
        add(Btn_save);
        Btn_save.setBounds(260, 510, 75, 29);

        txt_Liscense.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_Liscense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LiscenseActionPerformed(evt);
            }
        });
        add(txt_Liscense);
        txt_Liscense.setBounds(310, 240, 101, 20);

        txt_Issue.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Issue);
        txt_Issue.setBounds(310, 290, 101, 20);

        txt_Expiry.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Expiry);
        txt_Expiry.setBounds(310, 340, 101, 20);

        txt_Blood.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_Blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BloodActionPerformed(evt);
            }
        });
        add(txt_Blood);
        txt_Blood.setBounds(310, 390, 101, 20);

        Lbl_Liscense.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Liscense.setText("Liscense Number ");
        Lbl_Liscense.setToolTipText("");
        add(Lbl_Liscense);
        Lbl_Liscense.setBounds(120, 240, 130, 17);

        Lbl_Issue.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Issue.setText("Issue Date");
        Lbl_Issue.setToolTipText("");
        add(Lbl_Issue);
        Lbl_Issue.setBounds(120, 290, 70, 17);

        Lbl_Expiry.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Expiry.setText("Expiry Date");
        Lbl_Expiry.setToolTipText("");
        add(Lbl_Expiry);
        Lbl_Expiry.setBounds(120, 330, 78, 30);

        Lbl_Blood.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Blood.setText("Blood Group");
        Lbl_Blood.setToolTipText("");
        add(Lbl_Blood);
        Lbl_Blood.setBounds(120, 390, 86, 17);

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setText("Upload Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(110, 440, 130, 29);

        Lbl_Photo.setText("Photo");
        add(Lbl_Photo);
        Lbl_Photo.setBounds(320, 420, 100, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/liscense.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(120, 160, 72, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/back.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, -80, 1040, 930);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        // TODO add your handling code here:
        liscense.setLiscense_No(txt_Liscense.getText());
        liscense.setIssue_Date(txt_Issue.getText());
        liscense.setExpiry_Date(txt_Expiry.getText());
        liscense.setBlood_Group(txt_Blood.getText());

        
        JOptionPane.showMessageDialog(this, "your information has been saved.");
        
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void txt_BloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BloodActionPerformed

    private void txt_LiscenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LiscenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LiscenseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            Lbl_Photo.setIcon(ResizeImage(path));
            liscense.setPath(path);
        }
        //if the user click on save in Jfilechooser
        else if(result == JFileChooser.CANCEL_OPTION)
        {
            System.out.println("No File Select");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_save;
    private javax.swing.JLabel Lbl_Blood;
    private javax.swing.JLabel Lbl_Expiry;
    private javax.swing.JLabel Lbl_Issue;
    private javax.swing.JLabel Lbl_Liscense;
    private javax.swing.JLabel Lbl_Photo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_Blood;
    private javax.swing.JTextField txt_Expiry;
    private javax.swing.JTextField txt_Issue;
    private javax.swing.JTextField txt_Liscense;
    // End of variables declaration//GEN-END:variables
}
