/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Checkin;
import Model.Liscense;
import Model.Medical;
import Model.Person;
import Model.Savings;

/**
 *
 * @author chinmayi_shaligram
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form Final
     */
    
    Person person;              //person is an object of class Person 
    Model.Address address;
    Savings savings;
    Checkin checkin;
    Liscense liscense;
    Medical medical;
    
    public Final() {
        initComponents();
        
    person= new Person();
    address = new Model.Address();
    savings = new Savings();
    checkin = new Checkin();
    liscense = new Liscense();
    medical = new Medical();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Btn_Create_demo = new javax.swing.JButton();
        Btn_Create_Address = new javax.swing.JButton();
        Btn_View_Demo = new javax.swing.JButton();
        Btn_View_Adress = new javax.swing.JButton();
        Btn_View_Savings = new javax.swing.JButton();
        Btn_View_Checkings = new javax.swing.JButton();
        Btn_Create_Checkings = new javax.swing.JButton();
        Create_Medical = new javax.swing.JButton();
        Btn_View_Medical = new javax.swing.JButton();
        Btn_Create_License = new javax.swing.JButton();
        Btn_View_License = new javax.swing.JButton();
        Btn_View = new javax.swing.JButton();
        Btn_Create_Savings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1824, 650));
        setSize(new java.awt.Dimension(1100, 610));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 800));
        jPanel2.setLayout(null);

        Btn_Create_demo.setBackground(new java.awt.Color(204, 204, 255));
        Btn_Create_demo.setText("Create Person");
        Btn_Create_demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Create_demoActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Create_demo);
        Btn_Create_demo.setBounds(40, 130, 130, 29);

        Btn_Create_Address.setBackground(new java.awt.Color(204, 204, 255));
        Btn_Create_Address.setText("Create Address");
        Btn_Create_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Create_AddressActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Create_Address);
        Btn_Create_Address.setBounds(40, 180, 120, 29);

        Btn_View_Demo.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_Demo.setText("View Person ");
        Btn_View_Demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_DemoActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_Demo);
        Btn_View_Demo.setBounds(190, 130, 120, 30);

        Btn_View_Adress.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_Adress.setText("View Address");
        Btn_View_Adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_AdressActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_Adress);
        Btn_View_Adress.setBounds(190, 180, 120, 29);

        Btn_View_Savings.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_Savings.setText("View Savings");
        Btn_View_Savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_SavingsActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_Savings);
        Btn_View_Savings.setBounds(190, 230, 120, 29);

        Btn_View_Checkings.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_Checkings.setText("View Checkings");
        Btn_View_Checkings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_CheckingsActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_Checkings);
        Btn_View_Checkings.setBounds(170, 280, 150, 29);

        Btn_Create_Checkings.setBackground(new java.awt.Color(204, 204, 255));
        Btn_Create_Checkings.setText("Create Checkings");
        Btn_Create_Checkings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Create_CheckingsActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Create_Checkings);
        Btn_Create_Checkings.setBounds(20, 280, 139, 29);

        Create_Medical.setBackground(new java.awt.Color(204, 204, 255));
        Create_Medical.setText("Create Medical Records");
        Create_Medical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_MedicalActionPerformed(evt);
            }
        });
        jPanel2.add(Create_Medical);
        Create_Medical.setBounds(0, 400, 170, 29);

        Btn_View_Medical.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_Medical.setText("View medical Records");
        Btn_View_Medical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_MedicalActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_Medical);
        Btn_View_Medical.setBounds(170, 400, 160, 29);

        Btn_Create_License.setBackground(new java.awt.Color(204, 204, 255));
        Btn_Create_License.setText("Create Liscense");
        Btn_Create_License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Create_LicenseActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Create_License);
        Btn_Create_License.setBounds(20, 340, 130, 29);

        Btn_View_License.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View_License.setText("View Liscense");
        Btn_View_License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_View_LicenseActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View_License);
        Btn_View_License.setBounds(180, 340, 140, 29);

        Btn_View.setBackground(new java.awt.Color(204, 204, 255));
        Btn_View.setText("View Report");
        Btn_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ViewActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_View);
        Btn_View.setBounds(120, 460, 118, 29);

        Btn_Create_Savings.setBackground(new java.awt.Color(204, 204, 255));
        Btn_Create_Savings.setText("Create Savings");
        Btn_Create_Savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Create_SavingsActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Create_Savings);
        Btn_Create_Savings.setBounds(20, 230, 136, 29);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Demographic Information");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 40, 250, 30);

        SplitPane.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Create_demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Create_demoActionPerformed
        // TODO add your handling code here:
        Create_Person CreatePanel = new Create_Person(person);    //class name object name created and parameter passed
        SplitPane.setRightComponent(CreatePanel);                   //right Jpanel set on click button of person
    }//GEN-LAST:event_Btn_Create_demoActionPerformed

    private void Btn_Create_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Create_AddressActionPerformed
        // TODO add your handling code here:
        Create_Address Createpanel1 = new Create_Address(address);
        SplitPane.setRightComponent(Createpanel1);
    }//GEN-LAST:event_Btn_Create_AddressActionPerformed

    private void Btn_View_DemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_DemoActionPerformed
        // TODO add your handling code here:
        View_Person ViewPanel = new View_Person(person);    //class name object name created and parameter passed
        SplitPane.setRightComponent(ViewPanel);
    }//GEN-LAST:event_Btn_View_DemoActionPerformed

    private void Btn_View_AdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_AdressActionPerformed
        // TODO add your handling code here:
        View_Address ViewPanel1 = new View_Address(address);
        SplitPane.setRightComponent(ViewPanel1);
    }//GEN-LAST:event_Btn_View_AdressActionPerformed

    private void Btn_View_SavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_SavingsActionPerformed
        // TODO add your handling code here:
        View_Savings ViewPanel2 = new View_Savings(savings);
        SplitPane.setRightComponent(ViewPanel2);
    }//GEN-LAST:event_Btn_View_SavingsActionPerformed

    private void Btn_View_CheckingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_CheckingsActionPerformed
        // TODO add your handling code here:
        View_Checkin ViewPanel3 = new View_Checkin(checkin);
        SplitPane.setRightComponent(ViewPanel3);
        //        View_Checkin ViewPanel3 = new View_Checkin(checkin);
        //        SplitPane.setRightComponent(ViewPanel3);
    }//GEN-LAST:event_Btn_View_CheckingsActionPerformed

    private void Btn_Create_CheckingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Create_CheckingsActionPerformed
        // TODO add your handling code here:
        Create_Checkin CreatePanel3 = new Create_Checkin(checkin);
        SplitPane.setRightComponent(CreatePanel3);
    }//GEN-LAST:event_Btn_Create_CheckingsActionPerformed

    private void Create_MedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_MedicalActionPerformed
        // TODO add your handling code here:
        Create_Medical CreatePanel5 = new Create_Medical(medical);
        SplitPane.setRightComponent(CreatePanel5);
    }//GEN-LAST:event_Create_MedicalActionPerformed

    private void Btn_View_MedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_MedicalActionPerformed
        // TODO add your handling code here:
        View_Medical ViewPanel5 = new View_Medical(medical);
        SplitPane.setRightComponent(ViewPanel5);
    }//GEN-LAST:event_Btn_View_MedicalActionPerformed

    private void Btn_Create_LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Create_LicenseActionPerformed
        // TODO add your handling code here:
        Create_Liscense CreatePanel4 = new Create_Liscense(liscense);
        SplitPane.setRightComponent(CreatePanel4);
    }//GEN-LAST:event_Btn_Create_LicenseActionPerformed

    private void Btn_View_LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_View_LicenseActionPerformed
        // TODO add your handling code here:
        View_Liscense ViewPanel4 = new View_Liscense(liscense);
        SplitPane.setRightComponent(ViewPanel4);
    }//GEN-LAST:event_Btn_View_LicenseActionPerformed

    private void Btn_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ViewActionPerformed
        // TODO add your handling code here:
        View_Report ViewPanel6 = new View_Report(person,address, savings,checkin,liscense,medical);
        SplitPane.setRightComponent(ViewPanel6);
    }//GEN-LAST:event_Btn_ViewActionPerformed

    private void Btn_Create_SavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Create_SavingsActionPerformed
        // TODO add your handling code here
        Create_Savings CreatePanel2 = new Create_Savings(savings);
        SplitPane.setRightComponent(CreatePanel2);
    }//GEN-LAST:event_Btn_Create_SavingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Create_Address;
    private javax.swing.JButton Btn_Create_Checkings;
    private javax.swing.JButton Btn_Create_License;
    private javax.swing.JButton Btn_Create_Savings;
    private javax.swing.JButton Btn_Create_demo;
    private javax.swing.JButton Btn_View;
    private javax.swing.JButton Btn_View_Adress;
    private javax.swing.JButton Btn_View_Checkings;
    private javax.swing.JButton Btn_View_Demo;
    private javax.swing.JButton Btn_View_License;
    private javax.swing.JButton Btn_View_Medical;
    private javax.swing.JButton Btn_View_Savings;
    private javax.swing.JButton Create_Medical;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
