/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Liscense;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author chinmayi_shaligram
 */
public class View_Liscense extends javax.swing.JPanel {

    /**
     * Creates new form View_Liscense1
     */
    Liscense liscense;
    public View_Liscense(Liscense liscense) {
    initComponents();
        
     this.liscense = liscense;
     
    displayliscense();
    }

    public ImageIcon ResizeImage (String ImagePath){
    ImageIcon MyImage = new ImageIcon(ImagePath);
    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(120,120, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
        
    }
        
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Liscense = new javax.swing.JTextField();
        txt_Issue = new javax.swing.JTextField();
        txt_Expiry = new javax.swing.JTextField();
        txt_Blood = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Lbl_Liscense = new javax.swing.JLabel();
        Lbl_Issue = new javax.swing.JLabel();
        Lbl_Expiry = new javax.swing.JLabel();
        Lbl_Blood = new javax.swing.JLabel();
        Lbl_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setToolTipText("");
        setLayout(null);

        txt_Liscense.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Liscense);
        txt_Liscense.setBounds(320, 260, 101, 20);

        txt_Issue.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Issue);
        txt_Issue.setBounds(320, 300, 101, 20);

        txt_Expiry.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Expiry);
        txt_Expiry.setBounds(320, 340, 101, 20);

        txt_Blood.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_Blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BloodActionPerformed(evt);
            }
        });
        add(txt_Blood);
        txt_Blood.setBounds(320, 380, 101, 20);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Driver's Liscense");
        add(jLabel1);
        jLabel1.setBounds(160, 170, 317, 30);

        Lbl_Liscense.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Liscense.setText("Liscense Number ");
        Lbl_Liscense.setToolTipText("");
        add(Lbl_Liscense);
        Lbl_Liscense.setBounds(150, 260, 120, 17);

        Lbl_Issue.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Issue.setText("Issue Date");
        Lbl_Issue.setToolTipText("");
        add(Lbl_Issue);
        Lbl_Issue.setBounds(150, 300, 80, 17);

        Lbl_Expiry.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Expiry.setText("Expiry Date");
        Lbl_Expiry.setToolTipText("");
        add(Lbl_Expiry);
        Lbl_Expiry.setBounds(150, 340, 80, 30);

        Lbl_Blood.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Blood.setText("Blood Group");
        Lbl_Blood.setToolTipText("");
        add(Lbl_Blood);
        Lbl_Blood.setBounds(150, 390, 90, 17);

        Lbl_img.setText("Photo");
        add(Lbl_img);
        Lbl_img.setBounds(330, 420, 110, 60);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Image");
        add(jLabel3);
        jLabel3.setBounds(150, 430, 60, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/liscense.png")); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(130, 160, 72, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/back.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, -10, 1110, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BloodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Blood;
    private javax.swing.JLabel Lbl_Expiry;
    private javax.swing.JLabel Lbl_Issue;
    private javax.swing.JLabel Lbl_Liscense;
    private javax.swing.JLabel Lbl_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Blood;
    private javax.swing.JTextField txt_Expiry;
    private javax.swing.JTextField txt_Issue;
    private javax.swing.JTextField txt_Liscense;
    // End of variables declaration//GEN-END:variables

    private void displayliscense() {
        
       //To change body of generated methods, choose Tools | Templates.
       
       txt_Liscense.setText(liscense.getLiscense_No());
       txt_Issue.setText(liscense.getIssue_Date());
       txt_Expiry.setText(liscense.getExpiry_Date());
       txt_Blood.setText(liscense.getBlood_Group());
       
       Lbl_img.setIcon(ResizeImage(liscense.getPath()));
       
    }
}
