/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Savings;

/**
 *
 * @author chinmayi_shaligram
 */
public class View_Savings extends javax.swing.JPanel {

    /**
     * Creates new form View_Savings
     */
    Savings savings;
    public View_Savings(Savings savings) {
        initComponents();
        
        this.savings = savings;
        displaysavings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Accno = new javax.swing.JLabel();
        Lbl_Acctype = new javax.swing.JLabel();
        txt_BName2 = new javax.swing.JTextField();
        txt_BRouting = new javax.swing.JTextField();
        txt_AccNo = new javax.swing.JTextField();
        txt_Balance = new javax.swing.JTextField();
        txt_Acctype = new javax.swing.JTextField();
        Lbl_Savings = new javax.swing.JLabel();
        Lbl_BName = new javax.swing.JLabel();
        Lbl_Routing = new javax.swing.JLabel();
        Lbl_Balance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        Lbl_Accno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Accno.setText("Account Number");
        add(Lbl_Accno);
        Lbl_Accno.setBounds(150, 350, 120, 17);

        Lbl_Acctype.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Acctype.setText("Account Type");
        add(Lbl_Acctype);
        Lbl_Acctype.setBounds(150, 400, 100, 17);

        txt_BName2.setEditable(false);
        txt_BName2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_BName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BName2ActionPerformed(evt);
            }
        });
        add(txt_BName2);
        txt_BName2.setBounds(340, 200, 92, 20);

        txt_BRouting.setEditable(false);
        txt_BRouting.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_BRouting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BRoutingActionPerformed(evt);
            }
        });
        add(txt_BRouting);
        txt_BRouting.setBounds(340, 250, 92, 20);

        txt_AccNo.setEditable(false);
        txt_AccNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_AccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AccNoActionPerformed(evt);
            }
        });
        add(txt_AccNo);
        txt_AccNo.setBounds(340, 300, 92, 20);

        txt_Balance.setEditable(false);
        txt_Balance.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(txt_Balance);
        txt_Balance.setBounds(340, 350, 92, 20);

        txt_Acctype.setEditable(false);
        txt_Acctype.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txt_Acctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AcctypeActionPerformed(evt);
            }
        });
        add(txt_Acctype);
        txt_Acctype.setBounds(340, 400, 92, 20);

        Lbl_Savings.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Lbl_Savings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Savings.setText("Savings Account");
        add(Lbl_Savings);
        Lbl_Savings.setBounds(180, 110, 322, 30);

        Lbl_BName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_BName.setText("Bank Name");
        add(Lbl_BName);
        Lbl_BName.setBounds(150, 200, 90, 17);

        Lbl_Routing.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Routing.setText("Routing Number");
        add(Lbl_Routing);
        Lbl_Routing.setBounds(150, 250, 120, 17);

        Lbl_Balance.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Balance.setText("Balance");
        add(Lbl_Balance);
        Lbl_Balance.setBounds(150, 300, 60, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/savings.png")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(160, 90, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/back.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-80, -50, 1380, 860);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BName2ActionPerformed

    private void txt_BRoutingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BRoutingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BRoutingActionPerformed

    private void txt_AccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AccNoActionPerformed

    private void txt_AcctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AcctypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AcctypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Accno;
    private javax.swing.JLabel Lbl_Acctype;
    private javax.swing.JLabel Lbl_BName;
    private javax.swing.JLabel Lbl_Balance;
    private javax.swing.JLabel Lbl_Routing;
    private javax.swing.JLabel Lbl_Savings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_AccNo;
    private javax.swing.JTextField txt_Acctype;
    private javax.swing.JTextField txt_BName2;
    private javax.swing.JTextField txt_BRouting;
    private javax.swing.JTextField txt_Balance;
    // End of variables declaration//GEN-END:variables

    private void displaysavings() {
    //To change body of generated methods, choose Tools | Templates.
    txt_BName2.setText(savings.getBank_Name());
    txt_BRouting.setText(savings.getBank_Routing());
    txt_Balance.setText(savings.getBank_Balance());
    txt_AccNo.setText(savings.getAccount_No());
    txt_Acctype.setText(savings.getAccount_Type());
   
    
    }
}
