/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;
import Model.Person;


/**
 *
 * @author chinmayi_shaligram
 */
public class View_Person extends javax.swing.JPanel {

    /**
     * Creates new form View_Person
     */
    Person person;
    public View_Person(Person person) {
        initComponents();
        
    this.person = person;
    
    displayperson();
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Age = new javax.swing.JTextField();
        Txt_Ht = new javax.swing.JTextField();
        Txt_Wt = new javax.swing.JTextField();
        Txt_FN = new javax.swing.JTextField();
        Txt_SSN = new javax.swing.JTextField();
        Txt_LN = new javax.swing.JTextField();
        Lbl_Height = new javax.swing.JLabel();
        Lbl_Weight = new javax.swing.JLabel();
        Txt_Phno = new javax.swing.JTextField();
        Lbl_SSN = new javax.swing.JLabel();
        Txt_DOB = new javax.swing.JTextField();
        Lbl_Firstname = new javax.swing.JLabel();
        Lbl_LastName = new javax.swing.JLabel();
        Lbl_Phno = new javax.swing.JLabel();
        Lbl_DOB = new javax.swing.JLabel();
        Lbl_Age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        Txt_Age.setEditable(false);
        Txt_Age.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_AgeActionPerformed(evt);
            }
        });
        add(Txt_Age);
        Txt_Age.setBounds(490, 250, 95, 20);

        Txt_Ht.setEditable(false);
        Txt_Ht.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_HtActionPerformed(evt);
            }
        });
        add(Txt_Ht);
        Txt_Ht.setBounds(490, 300, 95, 20);

        Txt_Wt.setEditable(false);
        Txt_Wt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Wt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_WtActionPerformed(evt);
            }
        });
        add(Txt_Wt);
        Txt_Wt.setBounds(490, 350, 95, 20);

        Txt_FN.setEditable(false);
        Txt_FN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_FN);
        Txt_FN.setBounds(200, 250, 100, 20);

        Txt_SSN.setEditable(false);
        Txt_SSN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_SSN);
        Txt_SSN.setBounds(490, 400, 95, 20);

        Txt_LN.setEditable(false);
        Txt_LN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_LNActionPerformed(evt);
            }
        });
        add(Txt_LN);
        Txt_LN.setBounds(200, 300, 100, 20);

        Lbl_Height.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Height.setText("Height");
        add(Lbl_Height);
        Lbl_Height.setBounds(390, 300, 50, 17);

        Lbl_Weight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Weight.setText("Weight");
        add(Lbl_Weight);
        Lbl_Weight.setBounds(390, 350, 60, 17);

        Txt_Phno.setEditable(false);
        Txt_Phno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        Txt_Phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_PhnoActionPerformed(evt);
            }
        });
        add(Txt_Phno);
        Txt_Phno.setBounds(200, 350, 100, 20);

        Lbl_SSN.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_SSN.setText("SSN");
        add(Lbl_SSN);
        Lbl_SSN.setBounds(390, 400, 40, 17);

        Txt_DOB.setEditable(false);
        Txt_DOB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        add(Txt_DOB);
        Txt_DOB.setBounds(200, 400, 101, 20);

        Lbl_Firstname.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Firstname.setText("First Name");
        add(Lbl_Firstname);
        Lbl_Firstname.setBounds(70, 250, 73, 17);

        Lbl_LastName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_LastName.setText("Last Name");
        add(Lbl_LastName);
        Lbl_LastName.setBounds(70, 300, 80, 17);

        Lbl_Phno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Phno.setText("Phone Number ");
        add(Lbl_Phno);
        Lbl_Phno.setBounds(50, 350, 106, 17);

        Lbl_DOB.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_DOB.setText("Date of Birth");
        add(Lbl_DOB);
        Lbl_DOB.setBounds(60, 400, 100, 20);

        Lbl_Age.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Lbl_Age.setText("Age");
        add(Lbl_Age);
        Lbl_Age.setBounds(390, 250, 50, 17);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Person");
        add(jLabel4);
        jLabel4.setBounds(330, 130, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/person.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(220, 110, 80, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/chinmayi_shaligram/Library/Containers/com.microsoft.Word/Data/Library/Application Support/Microsoft/Office/16.0/WebServiceCache/AllUsers/NetBeansProjects/Assignment_1/src/Images/back.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-10, -50, 1630, 850);
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_AgeActionPerformed

    private void Txt_HtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_HtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_HtActionPerformed

    private void Txt_WtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_WtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_WtActionPerformed

    private void Txt_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_LNActionPerformed

    private void Txt_PhnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_PhnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_PhnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Age;
    private javax.swing.JLabel Lbl_DOB;
    private javax.swing.JLabel Lbl_Firstname;
    private javax.swing.JLabel Lbl_Height;
    private javax.swing.JLabel Lbl_LastName;
    private javax.swing.JLabel Lbl_Phno;
    private javax.swing.JLabel Lbl_SSN;
    private javax.swing.JLabel Lbl_Weight;
    private javax.swing.JTextField Txt_Age;
    private javax.swing.JTextField Txt_DOB;
    private javax.swing.JTextField Txt_FN;
    private javax.swing.JTextField Txt_Ht;
    private javax.swing.JTextField Txt_LN;
    private javax.swing.JTextField Txt_Phno;
    private javax.swing.JTextField Txt_SSN;
    private javax.swing.JTextField Txt_Wt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        //To change body of generated methods, choose Tools | Templates.
        Txt_FN.setText(person.getFirst_Name());
        Txt_LN.setText(person.getLast_Name());
        Txt_Phno.setText(person.getPhone_Num());
        Txt_DOB.setText(person.getDOB());
        Txt_Age.setText(person.getAge());
        Txt_Ht.setText(person.getHeight());
        Txt_Wt.setText(person.getWeight());
        Txt_SSN.setText(person.getSSN());
    }
}
